Implemented CRUD testing for mailings; Added task for other controller/routing methods

diff --git a/spec/test_app/script/full_suite b/spec/test_app/script/full_suite
--- a/spec/test_app/script/full_suite
+++ b/spec/test_app/script/full_suite
@@ -34,7 +34,7 @@ DBADAPTER=mysql bundle exec cucumber features && export CUC_MYSQL_SUCCESS=1
 
 unset RAILS_ENV
 
-if [ $MYSQL_SUCCESS -eq 0 ] ; then exit 1; fi
-if [ $SQLITE_SUCCESS -eq 0 ] ; then exit 1; fi
-if [ $CUC_MYSQL_SUCCESS -eq 0 ] ; then exit 1; fi
-if [ $CUC_SQLITE_SUCCESS -eq 0 ] ; then exit 1; fi
+if [ $MYSQL_SUCCESS -eq 0 ] ; then echo "Rspec Mysql Failed" && exit 1; fi
+if [ $SQLITE_SUCCESS -eq 0 ] ; then  echo "Rspec SQLite Failed" && exit 1; fi
+if [ $CUC_MYSQL_SUCCESS -eq 0 ] ; then  echo "Cucumber Mysql Failed" && exit 1; fi
+if [ $CUC_SQLITE_SUCCESS -eq 0 ] ; then  echo "Cucumber SQLite Failed" && exit 1; fi
