fixed script/fullsuite warnings; fixed cancan abilities for public urls

diff --git a/spec/test_app/script/full_suite b/spec/test_app/script/full_suite
--- a/spec/test_app/script/full_suite
+++ b/spec/test_app/script/full_suite
@@ -13,14 +13,14 @@ export CUC_SQLITE_SUCCESS=0
 DBADAPTER=sqlite bundle exec rspec spec && export SQLITE_SUCCESS=1
 DBADAPTER=sqlite bundle exec cucumber features && export CUC_SQLITE_SUCCESS=1
 
-if [ "$POSTGRES" -eq "1" ]; then
+if [ "$POSTGRES" = "1" ]; then
   #RUN FOR Postgresql
   cp config/database.postgres.local.yml config/database.yml
 
   bundle exec rake db:schema:load
   
   export PGSQL_SUCCESS=0
-  export CUCPGSQL_SUCCESS=0
+  export CUC_PGSQL_SUCCESS=0
 
   DBADAPTER=pg bundle exec rspec spec && export PGSQL_SUCCESS=1
   DBADAPTER=pg bundle exec cucumber features && export CUC_PGSQL_SUCCESS=1
@@ -43,10 +43,10 @@ DBADAPTER=mysql bundle exec cucumber features && export CUC_MYSQL_SUCCESS=1
 unset RAILS_ENV
 
 if [ $MYSQL_SUCCESS -eq 0 ] ; then echo "Rspec Mysql Failed" && exit 1; fi
-if [ $PGSQL_SUCCESS -eq 0 ] ; then echo "Rspec Pgsql Failed" && exit 1; fi
 if [ $SQLITE_SUCCESS -eq 0 ] ; then  echo "Rspec SQLite Failed" && exit 1; fi
 if [ $CUC_MYSQL_SUCCESS -eq 0 ] ; then  echo "Cucumber Mysql Failed" && exit 1; fi
-if [ "$POSTGRES" -eq "1" ] ; then 
+if [ $CUC_SQLITE_SUCCESS -eq 0 ] ; then  echo "Cucumber SQLite Failed" && exit 1; fi
+if [ "$POSTGRES" = "1" ] ; then 
+  if [ $PGSQL_SUCCESS -eq 0 ] ; then echo "Rspec Pgsql Failed" && exit 1; fi
   if [ $CUC_PGSQL_SUCCESS -eq 0 ] ; then  echo "Cucumber Pgsql Failed" && exit 1; fi
-  if [ $CUC_SQLITE_SUCCESS -eq 0 ] ; then  echo "Cucumber SQLite Failed" && exit 1; fi
 fi
