add testing of postgres to 'script/full_suite' and Gemfile and database config files; contact management testing; fixed deleteable soft deletion to work with rails3 better; fixed message search query to work with postgres; fixed subscription helper issue

diff --git a/spec/test_app/script/full_suite b/spec/test_app/script/full_suite
--- a/spec/test_app/script/full_suite
+++ b/spec/test_app/script/full_suite
@@ -2,12 +2,10 @@ export RAILS_ENV=test
 spring stop
 ./script/post_office start
 
-# RUN FOR SQLITE
-
 ./script/with_lock start
+# RUN FOR SQLITE
 cp config/database.sqlite.yml config/database.yml
 
-rm db/test.sqlite3
 spring rake db:schema:load
 
 export SQLITE_SUCCESS=0
@@ -16,13 +14,10 @@ export CUC_SQLITE_SUCCESS=0
 DBADAPTER=sqlite bundle exec rspec spec && export SQLITE_SUCCESS=1
 DBADAPTER=sqlite bundle exec cucumber features && export CUC_SQLITE_SUCCESS=1
 
-./script/with_lock stop
 
 #RUN FOR MYSQL
-cp config/database.local.yml config/database.yml
+cp config/database.mysql.local.yml config/database.yml
 
-mysqladmin -f drop mail_manager_test
-mysqladmin -f create mail_manager_test
 spring rake db:schema:load
 
 export MYSQL_SUCCESS=0
@@ -31,11 +26,25 @@ export CUCMYSQL_SUCCESS=0
 DBADAPTER=mysql bundle exec rspec spec && export MYSQL_SUCCESS=1
 DBADAPTER=mysql bundle exec cucumber features && export CUC_MYSQL_SUCCESS=1
 
+#RUN FOR Postgresql
+cp config/database.postgres.local.yml config/database.yml
+
+spring rake db:schema:load
+
+export PGSQL_SUCCESS=0
+export CUCPGSQL_SUCCESS=0
+
+DBADAPTER=pg bundle exec rspec spec && export PGSQL_SUCCESS=1
+DBADAPTER=pg bundle exec cucumber features && export CUC_PGSQL_SUCCESS=1
+
 ./script/post_office stop
+./script/with_lock stop
 
 unset RAILS_ENV
 
 if [ $MYSQL_SUCCESS -eq 0 ] ; then echo "Rspec Mysql Failed" && exit 1; fi
+if [ $PGSQL_SUCCESS -eq 0 ] ; then echo "Rspec Pgsql Failed" && exit 1; fi
 if [ $SQLITE_SUCCESS -eq 0 ] ; then  echo "Rspec SQLite Failed" && exit 1; fi
 if [ $CUC_MYSQL_SUCCESS -eq 0 ] ; then  echo "Cucumber Mysql Failed" && exit 1; fi
+if [ $CUC_PGSQL_SUCCESS -eq 0 ] ; then  echo "Cucumber Pgsql Failed" && exit 1; fi
 if [ $CUC_SQLITE_SUCCESS -eq 0 ] ; then  echo "Cucumber SQLite Failed" && exit 1; fi
